import { db } from '@/lib/db'
import { NextResponse } from 'next/server'

const products = [
  {
    name: 'Classic Mango Slices',
    slug: 'classic-mango-slices',
    description: 'Sweet, sun-dried mango perfection. Our Classic Mango Slices are made from premium Alphonso mangoes, carefully dehydrated to preserve their natural sweetness and vibrant flavor. Each bite delivers a burst of tropical sunshine that transports you to paradise.',
    price: 12.99,
    image: '🥭',
    category: 'Tropical',
    featured: true,
    rating: 4.8,
    reviewCount: 124,
    weight: '100g',
    ingredients: 'Premium Alphonso mangoes, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Crispy Apple Rings',
    slug: 'crispy-apple-rings',
    description: 'Light, crunchy apple rings with a hint of cinnamon. Made from freshly picked Granny Smith apples, these crispy rings are the perfect balance of tart and sweet with a warm cinnamon finish. A guilt-free snack that crunches with every bite.',
    price: 9.99,
    image: '🍎',
    category: 'Classic',
    featured: true,
    rating: 4.6,
    reviewCount: 89,
    weight: '100g',
    ingredients: 'Granny Smith apples, cinnamon, no added sugar',
    inStock: true,
  },
  {
    name: 'Tropical Pineapple Chunks',
    slug: 'tropical-pineapple-chunks',
    description: 'Sweet and tangy dried pineapple chunks that capture the essence of the tropics. These golden bites are dehydrated at peak ripeness to lock in the bold, vibrant pineapple flavor. Perfect as a snack or a tropical addition to your trail mix.',
    price: 11.49,
    image: '🍍',
    category: 'Tropical',
    featured: true,
    rating: 4.7,
    reviewCount: 96,
    weight: '120g',
    ingredients: 'Fresh pineapple, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Berry Medley Mix',
    slug: 'berry-medley-mix',
    description: 'A luxurious blend of strawberries, blueberries, and raspberries. Our Berry Medley combines three of nature finest berries into one irresistible mix. Each berry is individually dried to preserve its unique flavor profile, creating a symphony of berry goodness in every handful.',
    price: 14.99,
    image: '🫐',
    category: 'Berries',
    featured: true,
    rating: 4.9,
    reviewCount: 156,
    weight: '150g',
    ingredients: 'Strawberries, blueberries, raspberries, no added sugar',
    inStock: true,
  },
  {
    name: 'Golden Banana Chips',
    slug: 'golden-banana-chips',
    description: 'Crispy unsweetened banana chips that are naturally sweet and satisfyingly crunchy. Made from perfectly ripe Cavendish bananas, these golden chips are slowly dehydrated to achieve the ideal crispiness while maintaining their natural banana flavor.',
    price: 8.99,
    image: '🍌',
    category: 'Classic',
    featured: false,
    rating: 4.4,
    reviewCount: 67,
    weight: '120g',
    ingredients: 'Cavendish bananas, no added sugar, no oil',
    inStock: true,
  },
  {
    name: 'Zesty Orange Slices',
    slug: 'zesty-orange-slices',
    description: 'Candied orange slices with natural zest that deliver a bright, citrusy burst of flavor. These sun-kissed slices capture the full essence of Valencia oranges, from the sweet flesh to the aromatic, tangy peel. A sophisticated treat for citrus lovers.',
    price: 10.99,
    image: '🍊',
    category: 'Citrus',
    featured: false,
    rating: 4.5,
    reviewCount: 73,
    weight: '100g',
    ingredients: 'Valencia oranges, light cane sugar coating',
    inStock: true,
  },
  {
    name: 'Exotic Dragon Fruit',
    slug: 'exotic-dragon-fruit',
    description: 'Premium dried dragon fruit with its stunning magenta color and subtle sweetness. This exotic superfruit is carefully dehydrated to preserve its vibrant hue and delicate flavor. Rich in antioxidants and naturally beautiful, it is as nutritious as it is delicious.',
    price: 16.99,
    image: '🐉',
    category: 'Exotic',
    featured: false,
    rating: 4.7,
    reviewCount: 45,
    weight: '80g',
    ingredients: 'Red dragon fruit, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Sweet Kiwi Coins',
    slug: 'sweet-kiwi-coins',
    description: 'Chewy kiwi slices that pack a tangy-sweet punch. These emerald-green coins are made from sun-ripened kiwis, dehydrated to chewy perfection. The natural tartness of kiwi shines through, making these an addictive and wholesome snack.',
    price: 11.99,
    image: '🥝',
    category: 'Exotic',
    featured: false,
    rating: 4.3,
    reviewCount: 58,
    weight: '100g',
    ingredients: 'Fresh kiwi, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Cinnamon Pear Bites',
    slug: 'cinnamon-pear-bites',
    description: 'Spiced dried pear pieces infused with warm cinnamon. These tender pear bites combine the natural sweetness of Bartlett pears with the comforting warmth of Ceylon cinnamon. A cozy, autumn-inspired treat that is perfect any time of year.',
    price: 10.49,
    image: '🍐',
    category: 'Classic',
    featured: false,
    rating: 4.5,
    reviewCount: 42,
    weight: '120g',
    ingredients: 'Bartlett pears, Ceylon cinnamon, no added sugar',
    inStock: true,
  },
  {
    name: 'Pomegranate Arils',
    slug: 'pomegranate-arils',
    description: 'Tart-sweet dried pomegranate seeds that burst with flavor. These ruby-red arils are carefully extracted and dehydrated to create a crunchy, tangy-sweet superfood snack. Packed with antioxidants and bursting with pomegranate essence, they are nature candy at its finest.',
    price: 15.99,
    image: '❤️',
    category: 'Exotic',
    featured: false,
    rating: 4.6,
    reviewCount: 38,
    weight: '90g',
    ingredients: 'Pomegranate arils, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Coconut Strips',
    slug: 'coconut-strips',
    description: 'Toasted coconut strips with a satisfying crunch and rich, nutty flavor. Made from freshly harvested Thai coconuts, these strips are lightly toasted to bring out their natural oils and deepen their tropical flavor. An irresistible snack for coconut enthusiasts.',
    price: 9.49,
    image: '🥥',
    category: 'Tropical',
    featured: false,
    rating: 4.4,
    reviewCount: 55,
    weight: '110g',
    ingredients: 'Fresh Thai coconut, lightly toasted, no added sugar',
    inStock: true,
  },
  {
    name: 'Passion Fruit Leather',
    slug: 'passion-fruit-leather',
    description: 'A roll of pure passion fruit leather that captures the intense tropical flavor of fresh passion fruit. This artisan fruit leather is made from 100% passion fruit puree, slow-dried into a chewy, tangy strip. It is the ultimate tropical indulgence in a convenient, rollable form.',
    price: 13.99,
    image: '🥭',
    category: 'Exotic',
    featured: false,
    rating: 4.8,
    reviewCount: 31,
    weight: '80g',
    ingredients: 'Passion fruit puree, no added sugar, no preservatives',
    inStock: true,
  },
]

export async function POST() {
  try {
    // Check if products already exist
    const existing = await db.product.count()
    if (existing > 0) {
      return NextResponse.json({ message: 'Products already seeded', count: existing })
    }

    const result = await db.product.createMany({
      data: products,
    })

    return NextResponse.json({ message: 'Products seeded successfully', count: result.count })
  } catch (error) {
    console.error('Error seeding products:', error)
    return NextResponse.json({ error: 'Failed to seed products' }, { status: 500 })
  }
}
