import { db } from '@/lib/db'
import { NextResponse } from 'next/server'

const products = [
  // ═══════════ TROPICAL ═══════════
  {
    name: 'Classic Mango Slices',
    slug: 'classic-mango-slices',
    description: 'Sweet, sun-dried mango perfection. Our Classic Mango Slices are made from premium Alphonso mangoes, carefully dehydrated to preserve their natural sweetness and vibrant flavor. Each bite delivers a burst of tropical sunshine that transports you to paradise.',
    price: 12.99,
    image: '/products/mango.png',
    category: 'Tropical',
    featured: true,
    rating: 4.8,
    reviewCount: 124,
    weight: '100g',
    ingredients: 'Premium Alphonso mangoes, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Tropical Pineapple Chunks',
    slug: 'tropical-pineapple-chunks',
    description: 'Sweet and tangy dried pineapple chunks that capture the essence of the tropics. These golden bites are dehydrated at peak ripeness to lock in the bold, vibrant pineapple flavor. Perfect as a snack or a tropical addition to your trail mix.',
    price: 11.49,
    image: '/products/pineapple.png',
    category: 'Tropical',
    featured: true,
    rating: 4.7,
    reviewCount: 96,
    weight: '120g',
    ingredients: 'Fresh pineapple, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Coconut Strips',
    slug: 'coconut-strips',
    description: 'Toasted coconut strips with a satisfying crunch and rich, nutty flavor. Made from freshly harvested Thai coconuts, these strips are lightly toasted to bring out their natural oils and deepen their tropical flavor. An irresistible snack for coconut enthusiasts.',
    price: 9.49,
    image: '/products/coconut.png',
    category: 'Tropical',
    featured: false,
    rating: 4.4,
    reviewCount: 55,
    weight: '110g',
    ingredients: 'Fresh Thai coconut, lightly toasted, no added sugar',
    inStock: true,
  },
  {
    name: 'Sunset Papaya Strips',
    slug: 'sunset-papaya-strips',
    description: 'Vibrant orange papaya strips that taste like a tropical sunset. Our papaya is harvested at peak sweetness from lush Caribbean orchards, then gently dehydrated to lock in its buttery texture and honeyed flavor. A naturally sweet escape in every bite.',
    price: 10.99,
    image: '/products/papaya.png',
    category: 'Tropical',
    featured: false,
    rating: 4.5,
    reviewCount: 62,
    weight: '100g',
    ingredients: 'Fresh Caribbean papaya, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Guava Paradise Bites',
    slug: 'guava-paradise-bites',
    description: 'Chewy dried guava slices bursting with tropical fragrance and sweet-tart flavor. These pink-hued gems are made from hand-picked tropical guavas, slowly dehydrated to concentrate their irresistible aroma and unique strawberry-pear taste profile.',
    price: 13.49,
    image: '/products/guava.png',
    category: 'Tropical',
    featured: true,
    rating: 4.6,
    reviewCount: 48,
    weight: '100g',
    ingredients: 'Fresh tropical guava, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Golden Jackfruit Chips',
    slug: 'golden-jackfruit-chips',
    description: 'Crispy jackfruit chips that deliver the unique sweet banana-pineapple flavor of this tropical giant. Each chip is thinly sliced from ripe jackfruit and slow-dehydrated until perfectly crunchy. A rare and exotic treat you will not find anywhere else.',
    price: 14.99,
    image: '/products/jackfruit.png',
    category: 'Tropical',
    featured: false,
    rating: 4.3,
    reviewCount: 29,
    weight: '90g',
    ingredients: 'Fresh ripe jackfruit, no added sugar, no oil',
    inStock: true,
  },
  {
    name: 'Lychee Gems',
    slug: 'lychee-gems',
    description: 'Delicate dried lychee with a floral, rose-like sweetness that melts in your mouth. These translucent gems are crafted from premium lychees harvested at the peak of their aromatic bloom, then carefully dried to preserve their perfume-like fragrance and tender chew.',
    price: 15.99,
    image: '/products/lychee.png',
    category: 'Tropical',
    featured: true,
    rating: 4.7,
    reviewCount: 37,
    weight: '80g',
    ingredients: 'Premium fresh lychee, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Star Fruit Crisps',
    slug: 'star-fruit-crisps',
    description: 'Stunning star-shaped fruit crisps with a sweet-tart tropical flavor. These golden stars are sliced from perfectly ripe star fruit and dehydrated into crunchy, visually striking snacks. As beautiful on a cheese board as they are delicious straight from the bag.',
    price: 12.49,
    image: '/products/starfruit.png',
    category: 'Tropical',
    featured: false,
    rating: 4.4,
    reviewCount: 33,
    weight: '90g',
    ingredients: 'Fresh star fruit, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Cantaloupe Ribbons',
    slug: 'cantaloupe-ribbons',
    description: 'Sweet, juicy cantaloupe dried into tender ribbons that melt with concentrated melon flavor. Our cantaloupe is vine-ripened under the hot sun, then sliced and dehydrated into these vibrant orange strips. Like summer in every bite, any time of year.',
    price: 10.49,
    image: '/products/cantaloupe.png',
    category: 'Tropical',
    featured: false,
    rating: 4.5,
    reviewCount: 41,
    weight: '100g',
    ingredients: 'Fresh cantaloupe melon, no added sugar, no preservatives',
    inStock: true,
  },

  // ═══════════ BERRIES ═══════════
  {
    name: 'Berry Medley Mix',
    slug: 'berry-medley-mix',
    description: 'A luxurious blend of strawberries, blueberries, and raspberries. Our Berry Medley combines three of nature finest berries into one irresistible mix. Each berry is individually dried to preserve its unique flavor profile, creating a symphony of berry goodness in every handful.',
    price: 14.99,
    image: '/products/berries.png',
    category: 'Berries',
    featured: true,
    rating: 4.9,
    reviewCount: 156,
    weight: '150g',
    ingredients: 'Strawberries, blueberries, raspberries, no added sugar',
    inStock: true,
  },
  {
    name: 'Strawberry Crisps',
    slug: 'strawberry-crisps',
    description: 'Intensely flavored dried strawberry slices that capture the essence of peak-season berries. Each slice is freeze-dried to preserve its vivid red color and concentrated sweetness. Pop them on their own or sprinkle over yogurt and oatmeal for a berry boost.',
    price: 13.99,
    image: '/products/strawberry.png',
    category: 'Berries',
    featured: true,
    rating: 4.8,
    reviewCount: 112,
    weight: '80g',
    ingredients: 'Fresh strawberries, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Wild Blueberry Bites',
    slug: 'wild-blueberry-bites',
    description: 'Tiny but mighty, these wild blueberries are dried to perfection for a burst of antioxidant-rich flavor. Smaller and more intensely flavored than cultivated berries, our wild blueberries deliver a concentrated punch of sweet-tart goodness in every handful.',
    price: 15.49,
    image: '/products/blueberry.png',
    category: 'Berries',
    featured: false,
    rating: 4.7,
    reviewCount: 87,
    weight: '100g',
    ingredients: 'Wild blueberries, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Raspberry Crumbles',
    slug: 'raspberry-crumbles',
    description: 'Tangy-sweet dried raspberry pieces that deliver an explosion of berry flavor. These ruby-red crumbles are made from perfectly ripe raspberries, gently dried to preserve their signature tartness and vibrant color. Ideal for snacking, baking, or topping desserts.',
    price: 14.49,
    image: '/products/raspberry.png',
    category: 'Berries',
    featured: false,
    rating: 4.6,
    reviewCount: 64,
    weight: '90g',
    ingredients: 'Fresh raspberries, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Dark Cherry Bites',
    slug: 'dark-cherry-bites',
    description: 'Rich, sweet-tart dried cherries with a deep, complex flavor that cherry lovers adore. These dark beauties are made from Montmorency cherries, slowly dried to develop their natural sweetness and signature tang. A sophisticated snack for the discerning palate.',
    price: 14.99,
    image: '/products/cherry.png',
    category: 'Berries',
    featured: false,
    rating: 4.6,
    reviewCount: 53,
    weight: '100g',
    ingredients: 'Montmorency cherries, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Cranberry Zing',
    slug: 'cranberry-zing',
    description: 'Bright, tangy dried cranberries with just a whisper of natural sweetness. These vibrant red gems are infused with a touch of apple juice to balance their natural tartness, creating an addictive sweet-sour snack. Perfect on salads, in trail mix, or by the handful.',
    price: 11.99,
    image: '/products/cranberry.png',
    category: 'Berries',
    featured: false,
    rating: 4.5,
    reviewCount: 71,
    weight: '120g',
    ingredients: 'Cranberries, apple juice concentrate, no refined sugar',
    inStock: true,
  },
  {
    name: 'Acai Superberries',
    slug: 'acai-superberries',
    description: 'Dried acai berries packed with powerful antioxidants and a deep, rich berry-chocolate flavor. These superfruit gems are freeze-dried to preserve their legendary nutritional profile and unique taste. The ultimate blend of indulgence and wellness in every bite.',
    price: 18.99,
    image: '/products/acai.png',
    category: 'Berries',
    featured: true,
    rating: 4.8,
    reviewCount: 44,
    weight: '70g',
    ingredients: 'Freeze-dried acai berries, no added sugar, no preservatives',
    inStock: true,
  },

  // ═══════════ CITRUS ═══════════
  {
    name: 'Zesty Orange Slices',
    slug: 'zesty-orange-slices',
    description: 'Candied orange slices with natural zest that deliver a bright, citrusy burst of flavor. These sun-kissed slices capture the full essence of Valencia oranges, from the sweet flesh to the aromatic, tangy peel. A sophisticated treat for citrus lovers.',
    price: 10.99,
    image: '/products/orange.png',
    category: 'Citrus',
    featured: false,
    rating: 4.5,
    reviewCount: 73,
    weight: '100g',
    ingredients: 'Valencia oranges, light cane sugar coating',
    inStock: true,
  },
  {
    name: 'Sunny Lemon Rings',
    slug: 'sunny-lemon-rings',
    description: 'Tangy dried lemon rings that deliver a zingy, refreshing citrus punch. These bright yellow rings are dehydrated with their peel intact for an intense, aromatic lemon experience. Perfect for snacking, garnishing cocktails, or adding a citrus zing to recipes.',
    price: 9.99,
    image: '/products/lemon.png',
    category: 'Citrus',
    featured: false,
    rating: 4.4,
    reviewCount: 51,
    weight: '100g',
    ingredients: 'Fresh lemons, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Lime Zest Wheels',
    slug: 'lime-zest-wheels',
    description: 'Intensely flavored dried lime wheels with an aromatic, tangy kick. These emerald-green wheels capture the bold, fragrant essence of fresh limes in a convenient dried form. Perfect for cocktail garnishes, recipe additions, or an adventurous citrus snack.',
    price: 9.99,
    image: '/products/lime.png',
    category: 'Citrus',
    featured: false,
    rating: 4.3,
    reviewCount: 39,
    weight: '90g',
    ingredients: 'Fresh limes, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Tangerine Dream Segments',
    slug: 'tangerine-dream-segments',
    description: 'Sweet, easy-to-love dried tangerine segments with a milder, honeyed citrus flavor. These golden-orange segments are made from premium Murcott tangerines, dried to chewy perfection. Their natural sweetness and gentle citrus tang make them irresistible to all ages.',
    price: 11.49,
    image: '/products/tangerine.png',
    category: 'Citrus',
    featured: true,
    rating: 4.7,
    reviewCount: 66,
    weight: '100g',
    ingredients: 'Murcott tangerines, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Ruby Grapefruit Slices',
    slug: 'ruby-grapefruit-slices',
    description: 'Beautiful dried grapefruit slices with a delightful bitter-sweet balance and stunning ruby hue. These rosy-pink slices capture the complex flavor profile of ruby red grapefruit, from its characteristic tangy bite to its underlying honeyed sweetness. A grown-up citrus treat.',
    price: 11.99,
    image: '/products/grapefruit.png',
    category: 'Citrus',
    featured: false,
    rating: 4.5,
    reviewCount: 42,
    weight: '100g',
    ingredients: 'Ruby red grapefruit, light honey glaze',
    inStock: true,
  },

  // ═══════════ EXOTIC ═══════════
  {
    name: 'Exotic Dragon Fruit',
    slug: 'exotic-dragon-fruit',
    description: 'Premium dried dragon fruit with its stunning magenta color and subtle sweetness. This exotic superfruit is carefully dehydrated to preserve its vibrant hue and delicate flavor. Rich in antioxidants and naturally beautiful, it is as nutritious as it is delicious.',
    price: 16.99,
    image: '/products/dragonfruit.png',
    category: 'Exotic',
    featured: false,
    rating: 4.7,
    reviewCount: 45,
    weight: '80g',
    ingredients: 'Red dragon fruit, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Sweet Kiwi Coins',
    slug: 'sweet-kiwi-coins',
    description: 'Chewy kiwi slices that pack a tangy-sweet punch. These emerald-green coins are made from sun-ripened kiwis, dehydrated to chewy perfection. The natural tartness of kiwi shines through, making these an addictive and wholesome snack.',
    price: 11.99,
    image: '/products/kiwi.png',
    category: 'Exotic',
    featured: false,
    rating: 4.3,
    reviewCount: 58,
    weight: '100g',
    ingredients: 'Fresh kiwi, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Pomegranate Arils',
    slug: 'pomegranate-arils',
    description: 'Tart-sweet dried pomegranate seeds that burst with flavor. These ruby-red arils are carefully extracted and dehydrated to create a crunchy, tangy-sweet superfood snack. Packed with antioxidants and bursting with pomegranate essence, they are nature candy at its finest.',
    price: 15.99,
    image: '/products/pomegranate.png',
    category: 'Exotic',
    featured: false,
    rating: 4.6,
    reviewCount: 38,
    weight: '90g',
    ingredients: 'Pomegranate arils, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Passion Fruit Leather',
    slug: 'passion-fruit-leather',
    description: 'A roll of pure passion fruit leather that captures the intense tropical flavor of fresh passion fruit. This artisan fruit leather is made from 100% passion fruit puree, slow-dried into a chewy, tangy strip. It is the ultimate tropical indulgence in a convenient, rollable form.',
    price: 13.99,
    image: '/products/passionfruit.png',
    category: 'Exotic',
    featured: true,
    rating: 4.8,
    reviewCount: 31,
    weight: '80g',
    ingredients: 'Passion fruit puree, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Persimmon Petals',
    slug: 'persimmon-petals',
    description: 'Honey-sweet dried persimmon slices with a rich, date-like flavor and silky texture. These deep orange petals are crafted from fully ripened Fuyu persimmons, slow-dried to develop their natural honeyed sweetness. A delicacy in Asian cuisine and a revelation for new discoverers.',
    price: 13.49,
    image: '/products/persimmon.png',
    category: 'Exotic',
    featured: false,
    rating: 4.5,
    reviewCount: 27,
    weight: '100g',
    ingredients: 'Ripe Fuyu persimmons, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Mango Chili Explosion',
    slug: 'mango-chili-explosion',
    description: 'Sweet mango meets fiery chili in this addictive sweet-spicy snack. Premium Alphonso mango slices are dusted with a blend of chili, lime, and sea salt for a flavor rollercoaster that starts sweet, turns tangy, and finishes with a warming kick. Not for the faint of heart.',
    price: 13.99,
    image: '/products/mango-chili.png',
    category: 'Exotic',
    featured: true,
    rating: 4.9,
    reviewCount: 89,
    weight: '100g',
    ingredients: 'Alphonso mangoes, chili powder, lime, sea salt',
    inStock: true,
  },
  {
    name: 'Watermelon Jerky',
    slug: 'watermelon-jerky',
    description: 'Thick, chewy watermelon jerky that captures the essence of summer in every bite. These ruby-red strips are made from seedless watermelon, slow-dehydrated into a surprisingly meaty, jerky-like texture with concentrated watermelon sweetness. A one-of-a-kind snacking experience.',
    price: 14.49,
    image: '/products/watermelon.png',
    category: 'Exotic',
    featured: false,
    rating: 4.4,
    reviewCount: 35,
    weight: '80g',
    ingredients: 'Seedless watermelon, no added sugar, no preservatives',
    inStock: true,
  },

  // ═══════════ CLASSIC ═══════════
  {
    name: 'Crispy Apple Rings',
    slug: 'crispy-apple-rings',
    description: 'Light, crunchy apple rings with a hint of cinnamon. Made from freshly picked Granny Smith apples, these crispy rings are the perfect balance of tart and sweet with a warm cinnamon finish. A guilt-free snack that crunches with every bite.',
    price: 9.99,
    image: '/products/apple.png',
    category: 'Classic',
    featured: true,
    rating: 4.6,
    reviewCount: 89,
    weight: '100g',
    ingredients: 'Granny Smith apples, cinnamon, no added sugar',
    inStock: true,
  },
  {
    name: 'Golden Banana Chips',
    slug: 'golden-banana-chips',
    description: 'Crispy unsweetened banana chips that are naturally sweet and satisfyingly crunchy. Made from perfectly ripe Cavendish bananas, these golden chips are slowly dehydrated to achieve the ideal crispiness while maintaining their natural banana flavor.',
    price: 8.99,
    image: '/products/banana.png',
    category: 'Classic',
    featured: false,
    rating: 4.4,
    reviewCount: 67,
    weight: '120g',
    ingredients: 'Cavendish bananas, no added sugar, no oil',
    inStock: true,
  },
  {
    name: 'Cinnamon Pear Bites',
    slug: 'cinnamon-pear-bites',
    description: 'Spiced dried pear pieces infused with warm cinnamon. These tender pear bites combine the natural sweetness of Bartlett pears with the comforting warmth of Ceylon cinnamon. A cozy, autumn-inspired treat that is perfect any time of year.',
    price: 10.49,
    image: '/products/pear.png',
    category: 'Classic',
    featured: false,
    rating: 4.5,
    reviewCount: 42,
    weight: '120g',
    ingredients: 'Bartlett pears, Ceylon cinnamon, no added sugar',
    inStock: true,
  },
  {
    name: 'Royal Apricot Halves',
    slug: 'royal-apricot-halves',
    description: 'Sun-ripened dried apricot halves with a velvety texture and rich, tangy-sweet flavor. These golden-orange gems are made from Turkish apricots, naturally sun-dried to preserve their buttery softness and intense apricot essence. A timeless classic elevated to premium quality.',
    price: 11.99,
    image: '/products/apricot.png',
    category: 'Classic',
    featured: false,
    rating: 4.6,
    reviewCount: 76,
    weight: '120g',
    ingredients: 'Turkish apricots, no added sugar, no sulfites',
    inStock: true,
  },
  {
    name: 'Summer Peach Rings',
    slug: 'summer-peach-rings',
    description: 'Sweet, chewy dried peach rings that capture the juicy essence of a perfect summer peach. These golden rings are made from tree-ripened Georgia peaches, slowly dehydrated into tender, aromatic rings. Close your eyes and taste the orchard sunshine.',
    price: 12.49,
    image: '/products/peach.png',
    category: 'Classic',
    featured: true,
    rating: 4.7,
    reviewCount: 83,
    weight: '110g',
    ingredients: 'Georgia peaches, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Velvet Fig Halves',
    slug: 'velvet-fig-halves',
    description: 'Luxuriously sweet dried fig halves with a jammy, honeyed center. These Mediterranean figs are sun-dried until their natural sugars caramelize into a rich, complex sweetness. With their tender exterior and luscious interior, they are the epitome of dried fruit luxury.',
    price: 13.99,
    image: '/products/fig.png',
    category: 'Classic',
    featured: false,
    rating: 4.6,
    reviewCount: 49,
    weight: '110g',
    ingredients: 'Mediterranean figs, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Dark Plum Prunes',
    slug: 'dark-plum-prunes',
    description: "Impossibly juicy dried plums with a deep, wine-like sweetness and silky texture. These premium prunes are made from sun-ripened d'Agen plums, slow-dried to develop their characteristic rich, complex flavor. Naturally sweet and wonderfully satisfying.",
    price: 10.99,
    image: '/products/plum.png',
    category: 'Classic',
    featured: false,
    rating: 4.4,
    reviewCount: 57,
    weight: '130g',
    ingredients: "d'Agen plums, no added sugar, no preservatives",
    inStock: true,
  },
  {
    name: 'Medjool Date Jewels',
    slug: 'medjool-date-jewels',
    description: 'Premium Medjool dates, nature candy, with a caramel-like richness and creamy, melt-in-your-mouth texture. These royal dates are hand-selected for their exceptional size and quality. Each one is a bite-sized parcel of natural butterscotch perfection.',
    price: 16.49,
    image: '/products/date.png',
    category: 'Classic',
    featured: true,
    rating: 4.9,
    reviewCount: 98,
    weight: '150g',
    ingredients: 'Premium Medjool dates, no added sugar, no preservatives',
    inStock: true,
  },
  {
    name: 'Vineyard Grape Raisins',
    slug: 'vineyard-grape-raisins',
    description: 'Plump, juicy raisins made from premium Thompson seedless grapes, sun-dried to perfection. These are not your average raisins — each one is a tiny burst of concentrated grape sweetness with a satisfyingly chewy texture. The essential pantry staple, elevated.',
    price: 7.99,
    image: '/products/grape.png',
    category: 'Classic',
    featured: false,
    rating: 4.3,
    reviewCount: 94,
    weight: '150g',
    ingredients: 'Thompson seedless grapes, naturally sun-dried',
    inStock: true,
  },

  // ═══════════ MIXES ═══════════
  {
    name: 'Tropical Paradise Mix',
    slug: 'tropical-paradise-mix',
    description: 'An irresistible blend of mango, pineapple, papaya, coconut, and banana. Our signature Tropical Paradise Mix takes you on a flavor vacation with every handful. Each fruit is individually dried to its peak, then combined in perfect proportions for the ultimate tropical escape.',
    price: 15.99,
    image: '/products/tropical-mix.png',
    category: 'Mixes',
    featured: true,
    rating: 4.9,
    reviewCount: 142,
    weight: '200g',
    ingredients: 'Mango, pineapple, papaya, coconut, banana, no added sugar',
    inStock: true,
  },
]

export async function POST() {
  try {
    // Delete existing products and re-seed
    await db.product.deleteMany()

    const result = await db.product.createMany({
      data: products,
    })

    return NextResponse.json({ message: 'Products re-seeded successfully', count: result.count })
  } catch (error) {
    console.error('Error seeding products:', error)
    return NextResponse.json({ error: 'Failed to seed products' }, { status: 500 })
  }
}
